import fs from 'node:fs';
import { articleToMarkdown, buildArticlePrompt, editorialGate, slugify, type ArticleBrief } from '../lib/article-engine';
import { copyrightSafetyGate } from '../lib/copyright-safety';

type Trend = { title:string; link:string; source:string; sourceName?:string; publishedAt?:string; category:string; description?:string; eligible?:boolean; score?:number };
const stopWords = new Set(['about','after','again','also','been','being','could','from','have','into','more','most','over','said','some','than','that','their','there','these','they','this','what','when','which','with','will','would','your','technology','tech','digital','latest','news','update','updates','guide','how','today','artificial','intelligence','company','companies']);
const topicWords = (text='') => new Set(text.toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>=4&&!stopWords.has(w)));
const publisherName=(item:Trend)=>{const explicit=(item.sourceName||item.source||'').trim();if(explicit&&explicit.toLowerCase()!=='google news')return explicit;const m=item.description?.match(/<font[^>]*>([^<]+)<\/font>/i);return m?.[1]?.trim()||explicit||'Unknown publisher';};
const blockedPublishers=new Set(['facebook.com','facebook','reddit','pinterest','youtube','tiktok','x.com']);
const isCrediblePublisher=(name:string)=>{const n=name.toLowerCase().trim();return !!n&&!blockedPublishers.has(n)&&!n.includes('facebook.com');};
const existingTopicMatches=(candidate:Trend,existing:string[])=>{const candidateWords=topicWords(`${candidate.title} ${candidate.description??''}`);if(candidateWords.size<3)return false;return existing.some(text=>{const existingWords=topicWords(text);const shared=[...candidateWords].filter(w=>existingWords.has(w)).length;const union=new Set([...candidateWords,...existingWords]).size;return shared>=6 || (shared>=4 && union>0 && shared/union>=0.45);});};

type ProviderResult={text:string;provider:string};
const requestJson=async(url:string,headers:Record<string,string>,body:unknown):Promise<string>=>{const r=await fetch(url,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${r.status}: ${(await r.text()).slice(0,500)}`);const j=await r.json() as any;return j.choices?.[0]?.message?.content||j.output_text||j.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('')||'';};
const generateWithProviders=async(prompt:string):Promise<ProviderResult>=>{
  if(process.env.GROQ_API_KEY){try{const text=await requestJson('https://api.groq.com/openai/v1/chat/completions',{Authorization:`Bearer ${process.env.GROQ_API_KEY}`},{model:process.env.GROQ_MODEL||'openai/gpt-oss-20b',max_completion_tokens:3000,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]});if(text.trim())return{text,provider:'Groq'};console.log('Groq returned no usable text; trying next provider.');}catch(e){console.log(`Groq failed: ${e instanceof Error?e.message:String(e)}; trying next provider.`);}}
  if(process.env.GEMINI_API_KEY){try{const model=process.env.GEMINI_MODEL||'gemini-3.6-flash';const text=await requestJson(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{'x-goog-api-key':process.env.GEMINI_API_KEY},{contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}});if(text.trim())return{text,provider:'Gemini'};console.log('Gemini returned no usable text; trying next provider.');}catch(e){console.log(`Gemini failed: ${e instanceof Error?e.message:String(e)}; trying next provider.`);}}
  if(process.env.OPENAI_API_KEY){try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:prompt})});if(!r.ok)throw new Error(`${r.status}: ${(await r.text()).slice(0,500)}`);const j=await r.json() as any;const text=j.output_text||j.output?.flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==='output_text'&&x.text).map((x:any)=>x.text).join('')||'';if(text.trim())return{text,provider:'OpenAI'};}catch(e){console.log(`OpenAI failed: ${e instanceof Error?e.message:String(e)}.`);}}
  throw new Error('No AI provider is currently available.');
};

const parseModelJson=(raw:string):{title:string;description:string;content:string}=>{const text=raw.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'').trim();try{return JSON.parse(text);}catch{}const start=text.indexOf('{'),end=text.lastIndexOf('}');if(start>=0&&end>start){try{return JSON.parse(text.slice(start,end+1));}catch{}}throw new Error('AI output was not valid JSON');};

async function main(){
 const input='data/scored-trends.json',outputDir='content/articles';if(!fs.existsSync(input))process.exit(0);const payload=JSON.parse(fs.readFileSync(input,'utf8')) as {trends?:Trend[]};const trends=payload.trends??[];const existingTitles=new Set<string>();const existingTopics:string[]=[];if(fs.existsSync(outputDir))for(const file of fs.readdirSync(outputDir).filter(n=>n.endsWith('.md'))){const raw=fs.readFileSync(`${outputDir}/${file}`,'utf8');const title=raw.match(/^title:\s*"([\s\S]*?)"\s*$/m)?.[1];if(title)existingTitles.add(title.toLowerCase().trim());const category=raw.match(/^category:\s*"([\s\S]*?)"\s*$/m)?.[1]||'';const body=raw.replace(/^---[\s\S]*?---/,'').slice(0,4500);existingTopics.push(`${category} ${title??''} ${body}`);}
 const eligible=trends.filter(i=>i.eligible&&!existingTitles.has(i.title.toLowerCase().trim())&&!existingTopicMatches(i,existingTopics)).sort((a,b)=>(b.score??0)-(a.score??0));
 const findRelated=(candidate:Trend)=>{const pa=publisherName(candidate),words=topicWords(`${candidate.title} ${candidate.description??''}`);return trends.filter(item=>{if(item===candidate||item.link===candidate.link||existingTopicMatches(item,existingTopics))return false;const pb=publisherName(item);if(!isCrediblePublisher(pb)||pa.toLowerCase()===pb.toLowerCase())return false;const to=[...topicWords(item.title)].filter(w=>words.has(w)).length;const d=[...topicWords(item.description??'')].filter(w=>words.has(w)).length;return to>=2||(to>=1&&d>=2);}).sort((a,b)=>(b.score??0)-(a.score??0))[0];};
 const trend=eligible.find(candidate=>{const related=findRelated(candidate);if(!related)return false;return !existingTopicMatches({title:`${candidate.title} ${related.title}`,description:`${candidate.description??''} ${related.description??''}`,link:candidate.link,source:candidate.source,category:candidate.category,publishedAt:candidate.publishedAt},existingTopics);});
 if(!trend){console.log('No new eligible trend with independent credible source coverage found.');process.exit(0);}const pa=publisherName(trend),related=findRelated(trend);if(!related){console.log('No second independent publisher found for this topic; publication blocked.');process.exit(0);}
 const brief:ArticleBrief={title:trend.title,category:trend.category,angle:'Explain what changed, why it matters, what is known versus uncertain, and what readers should watch next. Use supplied sources as factual references only; write an original synthesis.',keyPoints:[trend.description??'Use only verified source context.',related.description??'Cross-check the development against the second independent publisher.'],sources:[{title:`${pa}: ${trend.title}`,url:trend.link,publishedAt:trend.publishedAt},{title:`${publisherName(related)}: ${related.title}`,url:related.link,publishedAt:related.publishedAt}]};
 const prompt=buildArticlePrompt(brief)+`\n\nOUTPUT FORMAT: Return ONLY one valid JSON object with exactly three string keys: title, description, content. No markdown fences, no commentary. Keep the article concise enough to fit the editorial gate. Aim for about 900-1100 words, with useful H2 headings. Write an original synthesis; never reproduce source sentences, paragraphs, or headlines. Do not invent facts, quotes, statistics, dates, or capabilities.`;fs.mkdirSync('data',{recursive:true});fs.writeFileSync('data/article-brief.json',JSON.stringify({generatedAt:new Date().toISOString(),brief,prompt},null,2));
 let output:ProviderResult;try{output=await generateWithProviders(prompt);}catch(e){console.log(`${e instanceof Error?e.message:String(e)} Publishing blocked.`);process.exit(0);}console.log(`Article generation provider: ${output.provider}`);
 let generated:{title:string;description:string;content:string};try{generated=parseModelJson(output.text);}catch(e){console.log(`${e instanceof Error?e.message:String(e)}; publishing blocked.`);process.exit(0);}if(!generated.title?.trim()||!generated.description?.trim()||!generated.content?.trim()){console.log('AI output is missing required article fields; publishing blocked.');process.exit(0);}if(existingTitles.has(generated.title.toLowerCase().trim())){console.log('Generated article title duplicates an existing article; publication blocked.');process.exit(0);}
 const article={...generated,slug:slugify(generated.title),category:brief.category,sources:brief.sources,generatedAt:new Date().toISOString()};const editorial=editorialGate(article);const copyright=copyrightSafetyGate({content:article.content,sources:article.sources.map(s=>s.url),images:[]});fs.writeFileSync('data/editorial-gate.json',JSON.stringify({generatedAt:new Date().toISOString(),provider:output.provider,editorial,copyright},null,2));if(!editorial.passed||!copyright.passed){console.log('Quality/copyright gate blocked publication.');process.exit(0);}fs.mkdirSync(outputDir,{recursive:true});fs.writeFileSync(`${outputDir}/${article.slug}.md`,articleToMarkdown(article));console.log(`Published article draft: ${article.slug}`);
}
main().catch(e=>{console.error(`Generator failed unexpectedly: ${e instanceof Error?e.message:String(e)}`);process.exit(1);});
