// TrendForge asset-gate validation marker v3
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { copyrightSafetyGate, type ImageCandidate } from '../lib/copyright-safety';
const dir='content/articles';
const files=fs.existsSync(dir)?fs.readdirSync(dir).filter(f=>f.endsWith('.md')).sort():[];
if(!files.length){console.log('No articles found; asset validation skipped.');process.exit(0);}
function field(text:string,key:string){const match=text.match(new RegExp(`^${key}:\\s*"([\\s\\S]*?)"\\s*$`,'m'));return match?match[1].replace(/\\"/g,'"'):'';}
let failed=false;const hashes=new Map<string,string>();
for(const file of files){const raw=fs.readFileSync(path.join(dir,file),'utf8');const parts=raw.split(/^---$/m);const front=parts[1]??'';const body=parts.slice(2).join('---').split(/^## Sources$/m)[0].trim();const image=field(front,'image'),imageAlt=field(front,'imageAlt'),imageSource=field(front,'imageSource'),imageLicense=field(front,'imageLicense'),generator=field(front,'imageGeneratedBy');const slug=field(front,'slug')||file.replace(/\.md$/,'');const localPath=image.startsWith('/Trendforge/')?path.join('public',image.slice('/Trendforge/'.length)):'';const candidate:ImageCandidate={url:image,source:imageSource,license:imageLicense};const gate=copyrightSafetyGate({content:body,sources:[...raw.matchAll(/\]\((https:\/\/[^)]+)\)/g)].map(m=>m[1]),images:[candidate]},{requireImages:true});let visualOk=false;let duplicate=false;if(localPath&&fs.existsSync(localPath)){const svg=fs.readFileSync(localPath,'utf8');const hash=crypto.createHash('sha256').update(svg).digest('hex');duplicate=hashes.has(hash);hashes.set(hash,slug);const visibleText=(svg.match(/<text\b/gi)||[]).length;const hasMetadata=/<title\b[^>]*>/.test(svg)&&/<desc\b[^>]*>/.test(svg);visualOk=svg.includes('viewBox="0 0 1200 630"')&&visibleText===0&&hasMetadata&&!generator.includes('topic renderer');}const ok=Boolean(image&&imageAlt&&imageSource&&imageLicense&&localPath&&fs.existsSync(localPath)&&gate.checks.safeImages&&generator==='TrendForge topic illustration engine v2'&&visualOk&&!duplicate);console.log(`${ok?'PASS':'FAIL'} image gate: ${slug}${duplicate?' (duplicate visual)':''}${visualOk?'':' (not v2 text-free illustration)'}`);if(!ok)failed=true;}
if(failed){console.error('One or more articles failed the image quality/safety gate. Publication blocked.');process.exit(1);}console.log(`All ${files.length} article images passed: topic-specific v2, text-free, unique, present, and safety metadata verified.`);
